import { Student, Cohort, ScheduleItem, FeedbackItem, JobFunnelStep, PartnerCompany } from './types';

export const COHORTS: Cohort[] = [
  {
    id: 'webdev-co18',
    name: 'Full-Stack Web Development (Co-18)',
    courseType: 'Web Development',
    weekCurrent: 6,
    weekTotal: 9,
    startDate: '2026-05-18',
    studentsCount: 12,
    averageGrade: 83.5,
    attendanceAverage: 92.4,
    status: 'active',
    mentors: ['Joshua', 'Nicole', 'Adrian']
  },
  {
    id: 'digimar-co09',
    name: 'Digital Marketing Specialist (Co-09)',
    courseType: 'Digital Marketing',
    weekCurrent: 3,
    weekTotal: 8,
    startDate: '2026-06-15',
    studentsCount: 10,
    averageGrade: 89.2,
    attendanceAverage: 95.1,
    status: 'active',
    mentors: ['Esther', 'Marcus']
  },
  {
    id: 'iosdev-co04',
    name: 'iOS Mobile Developer (Co-04)',
    courseType: 'iOS Development',
    weekCurrent: 9,
    weekTotal: 10,
    startDate: '2026-04-27',
    studentsCount: 8,
    averageGrade: 78.1,
    attendanceAverage: 88.5,
    status: 'active',
    mentors: ['Chin', 'Nicole']
  },
  {
    id: 'datasci-co02',
    name: 'Data Science & AI (Co-02)',
    courseType: 'Data Science',
    weekCurrent: 0,
    weekTotal: 12,
    startDate: '2026-07-20',
    studentsCount: 15,
    averageGrade: 0,
    attendanceAverage: 100,
    status: 'upcoming',
    mentors: ['Dr. Tan', 'Adrian']
  }
];

export const STUDENTS: Student[] = [
  // Web Development Co-18 Students
  {
    id: 'stu-wd01',
    name: 'Aaron Tan',
    email: 'aaron.tan@outlook.com',
    cohortId: 'webdev-co18',
    attendanceRate: 98,
    assignmentsCompleted: 10,
    assignmentsTotal: 10,
    currentGrade: 94,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Outstanding logical reasoning. Built an incredibly fast React + Node.js e-commerce app for his midterm. Actively helping fellow classmates during labs.',
    weeklyGrades: [90, 92, 95, 93, 96, 94]
  },
  {
    id: 'stu-wd02',
    name: 'Siti Aminah',
    email: 'siti.aminah@gmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 95,
    assignmentsCompleted: 9,
    assignmentsTotal: 10,
    currentGrade: 87,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Very creative UI designs. Excellent React component structure. Needs small push on advanced async/await error handling but catches up very fast.',
    weeklyGrades: [82, 85, 88, 87, 90, 87]
  },
  {
    id: 'stu-wd03',
    name: 'Jonathan Lim',
    email: 'jon.lim98@gmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 84,
    assignmentsCompleted: 6,
    assignmentsTotal: 10,
    currentGrade: 62,
    riskScore: 'High',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Missed multiple lab sessions due to personal constraints. Struggling with database schemas and joins. Midterm project was incomplete. Needs intensive 1-on-1 mentorship.',
    weeklyGrades: [75, 70, 65, 58, 60, 62]
  },
  {
    id: 'stu-wd04',
    name: 'Evelyn Ng',
    email: 'evelyn.ng@gmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 92,
    assignmentsCompleted: 8,
    assignmentsTotal: 10,
    currentGrade: 81,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Consistent worker. Great progress on frontend, takes some more time on server-side databases. Participates actively in standups.',
    weeklyGrades: [78, 80, 82, 79, 84, 81]
  },
  {
    id: 'stu-wd05',
    name: 'Viknesh Raj',
    email: 'viknesh.raj@yahoo.com',
    cohortId: 'webdev-co18',
    attendanceRate: 88,
    assignmentsCompleted: 7,
    assignmentsTotal: 10,
    currentGrade: 71,
    riskScore: 'Medium',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Good conceptual understanding, but struggles with code execution and debugging under time pressure. Missed 2 assignments. Showed improvement in Week 6.',
    weeklyGrades: [75, 72, 68, 70, 72, 71]
  },
  {
    id: 'stu-wd06',
    name: 'Chloe Wong',
    email: 'chloe.wong@student.next.my',
    cohortId: 'webdev-co18',
    attendanceRate: 100,
    assignmentsCompleted: 10,
    assignmentsTotal: 10,
    currentGrade: 96,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Flawless execution of coding exercises. Built a full-featured real-time chat with WebSockets as a side project. Highly recommend as a junior full-stack developer.',
    weeklyGrades: [94, 96, 95, 98, 96, 96]
  },
  {
    id: 'stu-wd07',
    name: 'Muhammad Daniel',
    email: 'daniel.suhaimi@hotmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 91,
    assignmentsCompleted: 8,
    assignmentsTotal: 10,
    currentGrade: 79,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Strong in CSS and Tailwind UI. Working hard on Express server. Needs guidance on structured state management in React.',
    weeklyGrades: [76, 78, 80, 78, 82, 79]
  },
  {
    id: 'stu-wd08',
    name: 'Melissa Low',
    email: 'mel.low99@gmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 96,
    assignmentsCompleted: 10,
    assignmentsTotal: 10,
    currentGrade: 91,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Quiet but extremely methodical. Her code is extremely clean, structured, and well-commented. Midterm database model was optimized beautifully.',
    weeklyGrades: [86, 89, 90, 92, 91, 91]
  },
  {
    id: 'stu-wd09',
    name: 'Tariq Azeem',
    email: 'tariq.azeem@gmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 79,
    assignmentsCompleted: 5,
    assignmentsTotal: 10,
    currentGrade: 58,
    riskScore: 'High',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Facing connectivity and laptop performance issues which impact lab participation. Struggles with key programming concepts (loops, arrays, states). Will set up 1-on-1 diagnostic.',
    weeklyGrades: [68, 64, 60, 55, 52, 58]
  },
  {
    id: 'stu-wd10',
    name: 'Lim Wei Han',
    email: 'weihan.lim@gmail.com',
    cohortId: 'webdev-co18',
    attendanceRate: 94,
    assignmentsCompleted: 9,
    assignmentsTotal: 10,
    currentGrade: 84,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Great at problem solving. Midterm project featured solid API design. Active contributor during group work.',
    weeklyGrades: [80, 82, 85, 84, 88, 84]
  },
  {
    id: 'stu-wd11',
    name: 'Rachel Cheah',
    email: 'rachel.cheah@live.com',
    cohortId: 'webdev-co18',
    attendanceRate: 92,
    assignmentsCompleted: 8,
    assignmentsTotal: 10,
    currentGrade: 80,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Very visual learner. Her design implementation is stellar. Needs to improve confidence during peer reviews.',
    weeklyGrades: [78, 79, 81, 80, 82, 80]
  },
  {
    id: 'stu-wd12',
    name: 'Justin Fernandez',
    email: 'justin.f@outlook.com',
    cohortId: 'webdev-co18',
    attendanceRate: 90,
    assignmentsCompleted: 8,
    assignmentsTotal: 10,
    currentGrade: 78,
    riskScore: 'Medium',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Capable of writing excellent backend routes, but attendance has dropped slightly in Week 5-6. Needs monitoring.',
    weeklyGrades: [82, 80, 78, 75, 77, 78]
  },

  // Digital Marketing Co-09 Students
  {
    id: 'stu-dm01',
    name: 'Sarah Jenkins',
    email: 'sarah.j@gmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 100,
    assignmentsCompleted: 5,
    assignmentsTotal: 5,
    currentGrade: 96,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Exceptional copywriting skill. Midterm Google Ads strategy achieved the highest simulated CTR in cohort history.',
    weeklyGrades: [95, 96, 97]
  },
  {
    id: 'stu-dm02',
    name: 'Teoh Wei Keat',
    email: 'weikeat.teoh@gmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 96,
    assignmentsCompleted: 5,
    assignmentsTotal: 5,
    currentGrade: 90,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Strong analytical skills. Excellent execution on SEO keyword research and Google Analytics segmenting.',
    weeklyGrades: [88, 91, 91]
  },
  {
    id: 'stu-dm03',
    name: 'Aisha Rahman',
    email: 'aisha.r@gmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 75,
    assignmentsCompleted: 3,
    assignmentsTotal: 5,
    currentGrade: 60,
    riskScore: 'High',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Struggles with advertising budget optimization and numbers-heavy metrics. Missed 2 classes last week. Outreach email sent.',
    weeklyGrades: [72, 65, 43]
  },
  {
    id: 'stu-dm04',
    name: 'Nicholas Lau',
    email: 'nicholas.l@hotmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 98,
    assignmentsCompleted: 5,
    assignmentsTotal: 5,
    currentGrade: 88,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Very strong social media content ideas. Videos generated for the mock campaign were highly engaging.',
    weeklyGrades: [86, 89, 89]
  },
  {
    id: 'stu-dm05',
    name: 'Fiona Chan',
    email: 'fiona.c@outlook.com',
    cohortId: 'digimar-co09',
    attendanceRate: 92,
    assignmentsCompleted: 4,
    assignmentsTotal: 5,
    currentGrade: 82,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Consistently completes assignments. Creative approach to Facebook campaign targeting and demographic mapping.',
    weeklyGrades: [80, 83, 83]
  },
  {
    id: 'stu-dm06',
    name: 'Syed Hamzah',
    email: 'syed.hamzah@gmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 88,
    assignmentsCompleted: 4,
    assignmentsTotal: 5,
    currentGrade: 74,
    riskScore: 'Medium',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Solid marketing concepts, but struggles with the backend technical tools (Tag Manager, pixels setup).',
    weeklyGrades: [76, 75, 71]
  },
  {
    id: 'stu-dm07',
    name: 'Priya Mohan',
    email: 'priya.m97@gmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 94,
    assignmentsCompleted: 5,
    assignmentsTotal: 5,
    currentGrade: 92,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Outstanding brand building presentations. Perfect understanding of email marketing workflows and copy.',
    weeklyGrades: [90, 93, 93]
  },
  {
    id: 'stu-dm08',
    name: 'Brandon Yap',
    email: 'brandon.yap@gmail.com',
    cohortId: 'digimar-co09',
    attendanceRate: 90,
    assignmentsCompleted: 4,
    assignmentsTotal: 5,
    currentGrade: 80,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Interested in e-commerce marketing. Solid efforts on landing page optimization projects.',
    weeklyGrades: [78, 81, 81]
  },
  {
    id: 'stu-dm09',
    name: 'Tiffany Cheng',
    email: 'tiffany.cheng@student.next.my',
    cohortId: 'digimar-co09',
    attendanceRate: 94,
    assignmentsCompleted: 5,
    assignmentsTotal: 5,
    currentGrade: 87,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Excellent designer and copywriter. Consistently submitting top-tier projects.',
    weeklyGrades: [84, 88, 89]
  },
  {
    id: 'stu-dm10',
    name: 'Darren Lim',
    email: 'darren.lim@live.com',
    cohortId: 'digimar-co09',
    attendanceRate: 92,
    assignmentsCompleted: 4,
    assignmentsTotal: 5,
    currentGrade: 81,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Active in class. Good understanding of SEO frameworks.',
    weeklyGrades: [79, 82, 82]
  },

  // iOS Mobile Developer Co-04 Students
  {
    id: 'stu-ios01',
    name: 'Kevin Ng',
    email: 'kevin.ng95@gmail.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 96,
    assignmentsCompleted: 14,
    assignmentsTotal: 15,
    currentGrade: 92,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Placed',
    placedCompany: 'Carsome',
    role: 'Junior iOS Developer',
    notes: 'Strong background in computer science. Mastered SwiftUI, CoreData and networking very fast. Secured an offer 1 week before graduation!',
    weeklyGrades: [88, 90, 92, 91, 93, 92, 95, 92, 93]
  },
  {
    id: 'stu-ios02',
    name: 'Samantha Loo',
    email: 'sam.loo@gmail.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 98,
    assignmentsCompleted: 15,
    assignmentsTotal: 15,
    currentGrade: 95,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Superb SwiftUI layout intuition. Midterm app was polished to App Store standard. Highly organized and articulate.',
    weeklyGrades: [92, 94, 95, 94, 96, 95, 97, 95, 96]
  },
  {
    id: 'stu-ios03',
    name: 'Alex Tan',
    email: 'alex.tan99@outlook.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 72,
    assignmentsCompleted: 8,
    assignmentsTotal: 15,
    currentGrade: 54,
    riskScore: 'High',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Often absent from morning stands. Finding OOP concepts in Swift extremely tough. Midterm Swift package was broken. Requires targeted debug support immediately.',
    weeklyGrades: [65, 60, 58, 52, 48, 50, 55, 52, 54]
  },
  {
    id: 'stu-ios04',
    name: 'Patricia Lim',
    email: 'pat.lim@live.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 90,
    assignmentsCompleted: 13,
    assignmentsTotal: 15,
    currentGrade: 80,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Hard working student. Mastered Xcode constraints and layout. Working on improving asynchronous network testing.',
    weeklyGrades: [76, 78, 80, 81, 82, 79, 83, 80, 80]
  },
  {
    id: 'stu-ios05',
    name: 'Gary Khor',
    email: 'gary.k@gmail.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 84,
    assignmentsCompleted: 11,
    assignmentsTotal: 15,
    currentGrade: 70,
    riskScore: 'Medium',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Struggles with memory management and delegates. Great enthusiasm, but gets stuck easily without debugging help.',
    weeklyGrades: [72, 70, 74, 68, 70, 69, 71, 70, 70]
  },
  {
    id: 'stu-ios06',
    name: 'Wong Lay Hoon',
    email: 'layhoon.w@student.next.my',
    cohortId: 'iosdev-co04',
    attendanceRate: 92,
    assignmentsCompleted: 14,
    assignmentsTotal: 15,
    currentGrade: 84,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Understands concurrency and async Swift nicely. Creative capstone project design in progress.',
    weeklyGrades: [80, 82, 85, 84, 86, 83, 85, 84, 84]
  },
  {
    id: 'stu-ios07',
    name: 'Hazim Ishak',
    email: 'hazim.ishak@gmail.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 82,
    assignmentsCompleted: 10,
    assignmentsTotal: 15,
    currentGrade: 68,
    riskScore: 'Medium',
    status: 'Active',
    employmentStatus: 'Not Placed',
    notes: 'Good visual development skill. Needs to boost Swift backend and API integrations.',
    weeklyGrades: [70, 68, 72, 65, 68, 66, 70, 67, 68]
  },
  {
    id: 'stu-ios08',
    name: 'Isabella Fernandez',
    email: 'isabella.f@live.com',
    cohortId: 'iosdev-co04',
    attendanceRate: 90,
    assignmentsCompleted: 13,
    assignmentsTotal: 15,
    currentGrade: 82,
    riskScore: 'Low',
    status: 'Active',
    employmentStatus: 'Interviewing',
    notes: 'Dedicated. Consistent performance in all weekly Swift coding sprint assessments.',
    weeklyGrades: [78, 80, 82, 81, 84, 81, 83, 82, 82]
  }
];

export const SCHEDULE: ScheduleItem[] = [
  {
    id: 'sch-01',
    title: 'Advanced React: State Management with Context & Reducers',
    time: '09:30 AM - 12:30 PM',
    cohortName: 'Full-Stack Web Development (Co-18)',
    type: 'Lecture',
    instructor: 'Joshua',
    status: 'completed'
  },
  {
    id: 'sch-02',
    title: 'Hands-on Lab: Designing Relational Database Schemas',
    time: '02:00 PM - 05:00 PM',
    cohortName: 'Full-Stack Web Development (Co-18)',
    type: 'Lab Session',
    instructor: 'Nicole',
    status: 'completed'
  },
  {
    id: 'sch-03',
    title: 'Digital Advertising: Google Ads Search Campaign Setup',
    time: '10:00 AM - 01:00 PM',
    cohortName: 'Digital Marketing Specialist (Co-09)',
    type: 'Lecture',
    instructor: 'Esther',
    status: 'completed'
  },
  {
    id: 'sch-04',
    title: 'Advanced CoreData & Local Storage in iOS Apps',
    time: '09:00 AM - 12:00 PM',
    cohortName: 'iOS Mobile Developer (Co-04)',
    type: 'Lecture',
    instructor: 'Chin',
    status: 'completed'
  },
  {
    id: 'sch-05',
    title: '1-on-1 Code Reviews: API Endpoints & Middlewares',
    time: '02:00 PM - 05:30 PM',
    cohortName: 'Full-Stack Web Development (Co-18)',
    type: 'Review Session',
    instructor: 'Adrian',
    status: 'live'
  },
  {
    id: 'sch-06',
    title: 'Career Workshop: Mastering the Technical Phone Screen',
    time: '11:00 AM - 01:00 PM',
    cohortName: 'iOS Mobile Developer (Co-04)',
    type: 'Career Workshop',
    instructor: 'Nicole',
    status: 'upcoming'
  },
  {
    id: 'sch-07',
    title: 'Industry Speaker: Tech Trends in Fintech & E-Commerce',
    time: '03:00 PM - 04:30 PM',
    cohortName: 'All Active Cohorts',
    type: 'Guest Speaker',
    instructor: 'Guest: CTO of Carsome',
    status: 'upcoming'
  }
];

export const FEEDBACK: FeedbackItem[] = [
  {
    id: 'fb-01',
    date: '2026-07-06',
    rating: 9,
    sentiment: 'Excellent',
    comment: 'The database schema lecture was super clean. Having Nicole debug our SQL live was extremely beneficial.',
    cohortName: 'Full-Stack Web Development (Co-18)'
  },
  {
    id: 'fb-02',
    date: '2026-07-05',
    rating: 10,
    sentiment: 'Excellent',
    comment: 'Joshua explained React state management using incredibly simple analogies! Midterm project feels much more doable now.',
    cohortName: 'Full-Stack Web Development (Co-18)'
  },
  {
    id: 'fb-03',
    date: '2026-07-04',
    rating: 5,
    sentiment: 'Poor',
    comment: 'The advertising metrics part went too fast. CTR, CPC, ROAS, CPA all scrambled together. Need more practice sheets.',
    cohortName: 'Digital Marketing Specialist (Co-09)'
  },
  {
    id: 'fb-04',
    date: '2026-07-03',
    rating: 8,
    sentiment: 'Good',
    comment: 'Xcode layouts are frustrating but Chin is super patient. He stayed 45 minutes extra to help us with constraint errors.',
    cohortName: 'iOS Mobile Developer (Co-04)'
  },
  {
    id: 'fb-05',
    date: '2026-07-02',
    rating: 7,
    sentiment: 'Neutral',
    comment: 'Standups are great, but sometimes they take too long. Maybe limit student updates to 1 minute each.',
    cohortName: 'Full-Stack Web Development (Co-18)'
  }
];

export const JOB_FUNNEL: JobFunnelStep[] = [
  { stage: 'Total Graduates', count: 184, percentage: 100 },
  { stage: 'Resumes Optimized', count: 175, percentage: 95 },
  { stage: 'First Round Interviews', count: 142, percentage: 77 },
  { stage: 'Technical Reviews', count: 115, percentage: 62 },
  { stage: 'Offers Extended', count: 98, percentage: 53 },
  { stage: 'Placed / Employed', count: 88, percentage: 48 }
];

export const PARTNERS: PartnerCompany[] = [
  { name: 'Carsome', industry: 'Automotive / E-Commerce', hiresCount: 16, logoColor: '#F59E0B' },
  { name: 'Grab', industry: 'Decacorn / On-Demand', hiresCount: 12, logoColor: '#10B981' },
  { name: 'Shopee', industry: 'E-Commerce Giant', hiresCount: 11, logoColor: '#EA580C' },
  { name: 'Maybank', industry: 'Banking / Fintech', hiresCount: 8, logoColor: '#FBBF24' },
  { name: 'Mindvalley', industry: 'Edtech / Media', hiresCount: 6, logoColor: '#8B5CF6' },
  { name: 'Fave', industry: 'Fintech / Payments', hiresCount: 5, logoColor: '#EC4899' }
];
